/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.base.dao;

import org.base.dao.searches.IDataMappingStrategy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Map;
import org.base.dao.datasources.connections.AbstractConnectionPool;
import org.base.dao.exceptions.ExceptionDBDuplicateEntry;
import org.base.dao.exceptions.ExceptionDBUnknownError;

/**
 *
 * @author martin
 */
public abstract class DAOAutonumeric extends DAOBase {
    
    protected abstract String getAutonumericFieldName();
    
    public DAOAutonumeric(String dataSourceContextName, IDataMappingStrategy toObjectMapper) {
        super(dataSourceContextName, toObjectMapper);
    }
    
    @Override
    public String getKeyFields() {
        return getAutonumericFieldName();
    }
    
    public int insertReturningId(Object objModelo) throws ExceptionDBDuplicateEntry {
        return insertReturningId(objModelo, getContextualConnection());            
    }
    
    public int insertReturningId(Object objModelo, Connection conn) throws ExceptionDBDuplicateEntry {
        int intId = 0;
        PreparedStatement pstm = null;

        try {
            StatementData stmtData = createInsertionData(getInsertionMap(objModelo));
            //pstm = prepareStatement(tryFixQuery(stmtData.getQuery()), stmtData.getParams(), conn);
            pstm = prepareStatementAutogeneratedKey(stmtData.getQuery(), stmtData.getParams(), conn);
            pstm.executeUpdate();  
            ResultSet rs = pstm.getGeneratedKeys(); 
            if (rs != null && rs.next()) {
                Map<String, Object> autoKeysMap = DAOUtils.rowToMap(rs);
                if(autoKeysMap.containsKey(getAutonumericFieldName())) intId = (Integer)autoKeysMap.get(getAutonumericFieldName());
                else {
                    Object [] a = autoKeysMap.keySet().toArray();
                    intId = (Integer)autoKeysMap.get((String)a[0]);
                }
                //intId = Integer.parseInt(rs.getString(getAutonumericFieldName()));
            }
            return intId;
        } catch (SQLException ex) {
            SQLException exx = null;
            if (ex.getSQLState() == null) {
                exx = (SQLException) ex.getCause();
            }
            if (exx != null && exx.getSQLState().equals(AbstractConnectionPool.UNIQUE_VIOLATION)) {
                throw new ExceptionDBDuplicateEntry();
            } else {
                DAOPackage.log(ex);
                throw new ExceptionDBUnknownError(ex);
            }
        } catch (Exception unknown) {
            DAOPackage.log(unknown);
            throw new ExceptionDBUnknownError(unknown);
        } finally {
            //try {
                closeContextualStatement(pstm);
                closeContextualConnection(conn);
            //} catch (SQLException ex) {
                //throw new SistemaExcepcion(ex);
            //}
        }
    }
    
    private String tryFixQuery(String sql) {
        if(!sql.toLowerCase().contains("returning")) {
            return sql + " RETURNING " + getAutonumericFieldName();
        }
        return sql;
    }
}
